plugins {
    id 'java'
    id 'org.springframework.boot' version '3.3.5'
    id 'io.spring.dependency-management' version '1.1.6'
}

group = 'com.ride'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-mongodb'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
//	implementation 'org.springframework.cloud:spring-cloud-aws-messaging:2.2.6.RELEASE'
    implementation 'com.sun.mail:jakarta.mail:2.0.1'
    implementation 'io.awspring.cloud:spring-cloud-aws-starter-sqs:3.0.0'
    implementation 'io.awspring.cloud:spring-cloud-aws-starter-sns:3.0.0'
    implementation 'software.amazon.awssdk:sqs:2.20.14'
    implementation 'software.amazon.awssdk:sns:2.20.14'
    implementation 'org.json:json:20171018'
    implementation('com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.9.8')

}

tasks.named('test') {
    useJUnitPlatform()
}
