version: '3.5'
services:
    cart:
        container_name: cart
        restart: always
        environment:
            MONGODB_DB: shopping-cart
            MONGODB_URI: mongodb://mongo:27017/shopping-cart
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - 8086:8086
        networks:
            - ms-net

networks:
    ms-net:
        external: true