version: '3.5'
services:
    eureka-server:
        container_name: eureka-server
        restart: always
        environment:
            - SPRING_APPLICATION_NAME=eureka-server
            - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
            - EUREKA_CLIENT_FETCH_REGISTRY=false
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - 8761:8761
        networks:
            ms-net:
                aliases:
                    - eureka-server.docker


networks:
    ms-net:
        external: true

