version: '3.5'
services:
    gateway:
        container_name: gateway
        restart: always
        environment:
            eureka.client.serviceUrl.defaultZone: http://eureka-server.docker:8761/eureka/
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - 8060:8060
        networks:
            ms-net:
                aliases:
                    - gateway.docker


networks:
    ms-net:
        external: true