version: '3.5'
services:

    product-command:
        container_name: product-command
        restart: always
        build:
            context: .
            dockerfile: ./Dockerfile
        environment:
            eureka.client.serviceUrl.defaultZone: http://eureka-server.docker:8761/
        ports:
            - 8088:8088
        networks:
            ms-net:
                aliases:
                    - product-command.docker


networks:
    ms-net:
        external: true
