spring.application.name=Goober
server.port=9092
# AWS SNS Configuration
aws.sns.topic.arn=<arn>

# AWS SQS Configuration
aws.sqs.driver.queue=driverqueue
aws.sqs.pricing.queue=pricingQueue
aws.sqs.notification.queue=NotificationQueue

# AWS Region
aws.region=us-east-1

# AWS Credentials
aws.credentials.access-key=<access-key>
aws.credentials.secret-key=<secret-key>


#Mail properties
email.port=993
mail.imaps.username=<email>
mail.imaps.password=<passcode>
#
#spring.data.redis.host=localhost
#spring.data.redis.port=6379
#spring.data.redis.database=0

event.deduplication.ttl=600
