spring:
  security:
    oauth2:
      client:
        registration:
          my-client:
            client-id: 1080184469568-apl20tffhv0fthvevi6uh44bqlj7ambk.apps.googleusercontent.com
            client-secret: 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
            authorizationGrantType: authorization_code
            redirectUri: http://localhost:8089/login/oauth2/code/example
            scope: read,write
            provider: your-provider
        provider:
          your-provider:
            authorizationUri: https://example.com/oauth2/authorize
            tokenUri: https://example.com/oauth2/token
            userInfoUri: https://example.com/oauth2/userinfo
            userNameAttribute: id
