spring.application.name=bff
server.port=8081

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.database=0

# Enable actuator endpoints
management.endpoints.web.exposure.include=metrics,health
management.endpoint.metrics.access=unrestricted
management.prometheus.metrics.export.enabled=true