version: '3.5'
services:
    user-service:
        container_name: user-service
        restart: always
        environment:
            MYSQL_DATABASE: user
            MYSQL_URI: jdbc:mariadb://mariadb.docker:3306
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - 8084:8084
        networks:
            ms-net:
                aliases:
                    - user-service.docker


networks:
    ms-net:
        external: true
