spring.application.name=security-microsoftAuth

server.port=4000

google.client.id=1080184469568-apl20tffhv0fthvevi6uh44bqlj7ambk.apps.googleusercontent.com
google.client.secret=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
google.redirect.uri=http://localhost:4000/google/auth


